# Generated by Django 4.0.6 on 2022-07-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.TextField()),
                ('feed_img', models.TextField()),
                ('feed_content', models.TextField()),
            ],
            options={
                'db_table': 'Feed',
            },
        ),
    ]
