# Generated by Django 4.0.6 on 2022-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.TextField()),
                ('User_ID', models.TextField()),
                ('reply', models.TextField()),
            ],
            options={
                'db_table': 'Reply',
            },
        ),
    ]
