# Generated by Django 4.1 on 2022-08-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reply_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='subject',
            new_name='diary',
        ),
    ]
