# Generated by Django 4.1 on 2022-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_subject_reply_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
