# Generated by Django 4.0.6 on 2022-07-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_comment',
            field=models.TextField(default=None),
        ),
    ]
